name: Cove Pages

on:
  push:
    branches: [pages]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      COVE_FQDN: ${{ vars.COVE_FQDN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        id: pages
        uses: http://forgejo:3000/cove/configure-pages@main

      - name: Build with Hugo
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}"

      - name: Upload artifact
        id: upload
        uses: http://forgejo:3000/cove/upload-pages-artifact@main
        with:
          path: public/

      - name: Deploy
        uses: http://forgejo:3000/cove/deploy-pages@main
        with:
          artifact_id: ${{ steps.upload.outputs.artifact_id }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
