---
- name: Read from macOS Keychain
  ansible.builtin.command:
    argv:
      - security
      - find-generic-password
      - -a
      - "{{ keystore_account | default(ansible_user_id) }}"
      - -s
      - "{{ keystore_service }}"
      - -w
  when: ansible_system == 'Darwin'
  changed_when: false
  no_log: true
  register: keystore_result

- name: Read from libsecret (Linux)
  ansible.builtin.command:
    argv:
      - secret-tool
      - lookup
      - service
      - "{{ keystore_service }}"
      - account
      - "{{ keystore_account | default(ansible_user_id) }}"
  when: ansible_system == 'Linux'
  changed_when: false
  no_log: true
  register: keystore_result
