[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cove-cli"
version = "0.1.0"
description = "Cove management CLI"
requires-python = ">=3.11"
dependencies = [
    "click",
    "pyyaml>=6.0.3",
    "requests>=2.33.0",
]

[project.scripts]
cove = "cove.cli:app"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.build.targets.wheel]
packages = ["cove"]

[dependency-groups]
dev = [
    "pytest",
]
