"""Generate a self-deleting bash script that creates 1Password items in bulk."""

import os
import secrets
import shlex
import string
import sys
from pathlib import Path
from typing import Any


def _read_yaml(path: Path) -> dict:
    try:
        import yaml
    except ImportError:
        import click
        raise click.ClickException("PyYAML required: pip install pyyaml")
    return yaml.safe_load(path.read_text())


def _generate_password(n: int) -> str:
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+[]{}"
    return "".join(secrets.choice(alphabet) for _ in range(n))


def _resolve_field_value(raw: str) -> tuple[str, bool]:
    stripped = raw.strip()
    if stripped.startswith("{{generate:") and stripped.endswith("}}"):
        inner = stripped[len("{{generate:"):-2].strip()
        n = int(inner)
        if n < 4:
            raise ValueError(
                f"Password length must be at least 4, got {n} from '{raw}'"
            )
        return _generate_password(n), True
    if stripped.startswith("{{file:") and stripped.endswith("}}"):
        inner = stripped[len("{{file:"):-2].strip()
        path = Path(os.path.expanduser(inner)).resolve()
        if not path.is_file():
            raise ValueError(f"File not found or not a regular file: {path}")
        if path.is_symlink():
            raise ValueError(f"Symlinks not allowed in {{file:}} placeholder: {path}")
        return path.read_text().rstrip(), True
    return raw, False


def _build_create_command(item: dict[str, Any]) -> tuple[list[str], list[str]]:
    title = item["title"]
    vault = item["vault"]
    category = item["category"]
    cmd = [
        "op",
        "item",
        "create",
        f"--vault={vault}",
        f"--title={title}",
        f"--category={category}",
    ]
    masked = list(cmd)
    for key, raw in (item.get("fields") or {}).items():
        value, is_secret = _resolve_field_value(str(raw))
        cmd.append(f"{key}={value}")
        masked.append(f"{key}={'***' if is_secret else value}")
    return cmd, masked


def _quote_argv(argv: list[str]) -> str:
    return shlex.join(argv)


def render_script(spec_path: Path) -> tuple[str, list[str]]:
    spec = _read_yaml(spec_path)
    items = spec.get("items") or []
    plan: list[str] = []
    create_lines: list[str] = []

    for item in items:
        cmd, masked = _build_create_command(item)
        plan.append(f"  + {item['vault']} / {item['title']} ({item['category']})")
        for arg in masked[6:]:
            plan.append(f"      {arg}")

        title = shlex.quote(item["title"])
        vault = shlex.quote(item["vault"])
        create_lines.append(
            f"""
if op item get {title} --vault={vault} >/dev/null 2>&1; then
  echo "skip: {title} already exists in {vault}"
else
  echo "create: {title} in {vault}"
  {_quote_argv(cmd)} >/dev/null
fi""".strip()
        )

    body_inner = "\n\n".join(create_lines)
    script = f"""#!/usr/bin/env bash
# Generated by `cove creds 1p-bulk-write`. Self-deleting on success.
set -euo pipefail

{body_inner}

rm -f -- "$0"
echo "done. script removed."
"""
    return script, plan
