"""Host vars state management — auto-detect and persist PII overlay."""

import json
import os
import platform
import re
import subprocess
from pathlib import Path

import click
import yaml

_HOSTNAME_RE = re.compile(r"^[A-Za-z0-9-]+$")


def _state_hosts_dir() -> Path:
    return Path.home() / ".config" / "cove" / "state" / "hosts"


def _detect_admin_username() -> str:
    return os.environ.get("COVE_ADMIN_USERNAME") or os.environ.get("USER", "")


def _detect_admin_email() -> str:
    env_email = os.environ.get("COVE_ADMIN_EMAIL")
    if env_email:
        return env_email
    result = subprocess.run(
        ["git", "config", "user.email"],
        capture_output=True, text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        return result.stdout.strip()
    return ""


def _detect_op_vault() -> str:
    return os.environ.get("COVE_OP_VAULT") or "Private"


def _detect_ts_dns_name() -> str:
    env = os.environ.get("COVE_TS_DNS_NAME")
    if env:
        return env
    result = subprocess.run(
        ["tailscale", "status", "--json"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        try:
            data = json.loads(result.stdout)
            dns = data.get("Self", {}).get("DNSName", "")
            if dns:
                return dns.rstrip(".")
        except json.JSONDecodeError:
            click.echo(
                "Warning: tailscale status returned unparseable JSON; "
                "ts_dns_name falling back to 'localhost'.",
                err=True,
            )
    elif result.returncode != 0:
        click.echo(
            "Warning: `tailscale status` failed (exit "
            f"{result.returncode}); ts_dns_name falling back to 'localhost'.",
            err=True,
        )
    return "localhost"


def _detect_values() -> dict:
    return {
        "admin_username": _detect_admin_username(),
        "admin_email": _detect_admin_email(),
        "op_vault": _detect_op_vault(),
        "ts_dns_name": _detect_ts_dns_name(),
    }


def ensure_host_vars() -> Path:
    hosts_dir = _state_hosts_dir()
    hostname = platform.node().split(".")[0]
    if not _HOSTNAME_RE.match(hostname):
        raise click.ClickException(
            f"Hostname {hostname!r} contains invalid characters; "
            "cannot create host_vars file."
        )
    host_vars = hosts_dir / f"{hostname}.yml"

    if host_vars.exists():
        click.echo(f"Using existing host vars: {host_vars}")
        return host_vars

    hosts_dir.mkdir(parents=True, exist_ok=True)
    values = _detect_values()
    header = (
        "# Auto-generated by `cove up`. Edit values as needed;\n"
        "# re-running `cove up` will NOT overwrite this file.\n"
    )
    host_vars.write_text(header + yaml.dump(values))
    click.echo(f"Applying host vars: {host_vars}")
    return host_vars