---
cove_version: "0.1.0"
k3s_version: "v1.30"
kata_version: "3.8"
lima_version: "1.0"

lima_vm_cpus: 4
lima_vm_memory: 8192   # MB
lima_vm_disk: 60        # GB
lima_vm_name: cove

cove_data_dir: "{{ ansible_env.HOME }}/Documents/cove"
cove_projects_dir: "{{ ansible_env.HOME }}/Documents/projects"

cove_namespace: cove
cove_domain: cove.local
