server {
    listen 80;
    server_name git.cove.mbpbk-202602.taila90e7.ts.net ~^.+\.pages\.cove\..+$;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name git.cove.mbpbk-202602.taila90e7.ts.net;

    ssl_certificate     /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;

    location / {
        proxy_pass http://forgejo:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    server_name ~^.+\.pages\.cove\..+$;

    ssl_certificate     /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;

    root /data/pages/sites;

    set $owner_path "";
    if ($host ~ "^([^.]+)\.pages\.") {
        set $owner_path "/$1";
    }

    location / {
        try_files $owner_path/.index$uri $owner_path/.index$uri/index.html $owner_path$uri $owner_path$uri/index.html =404;
    }
}
