---
- name: Configure macOS resolver
  when: ansible_os_family == "Darwin"
  ansible.builtin.copy:
    content: |
      nameserver 192.168.5.2
    dest: /etc/resolver/cove.local
    mode: "0644"
  become: yes

- name: Configure Linux resolver
  when: ansible_os_family == "Debian"
  ansible.builtin.copy:
    content: |
      [Resolve]
      DNS=127.0.0.1
      Domains=~cove.local
    dest: /etc/systemd/resolved.conf.d/cove.conf
    mode: "0644"
  become: yes
  notify: restart systemd-resolved

- name: Apply CoreDNS custom zone
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'coredns-custom.yml') | from_yaml }}"
