---
- name: Install Lima (macOS)
  when: ansible_os_family == "Darwin"
  include_tasks: install-lima.yml

- name: Create Lima VM
  when: ansible_os_family == "Darwin"
  ansible.builtin.template:
    src: lima-k3s.yaml.j2
    dest: "{{ ansible_env.HOME }}/.lima/{{ lima_vm_name }}/lima.yaml"
    mode: "0644"

- name: Start Lima VM
  when: ansible_os_family == "Darwin"
  ansible.builtin.command:
    cmd: limactl start {{ lima_vm_name }}
    creates: "{{ ansible_env.HOME }}/.lima/{{ lima_vm_name }}/lima.yaml"
