---
- name: Download k3s binary
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-{{ ansible_architecture | replace('aarch64', 'arm64') | replace('x86_64', 'amd64') }}"
    dest: /usr/local/bin/k3s
    mode: "0755"
    checksum: "sha256:{{ lookup('file', 'k3s-checksums.txt') }}"

- name: Start k3s server
  ansible.builtin.command:
    cmd: k3s server --docker
    creates: /var/lib/rancher/k3s/server/token
